# -*- coding: utf-8 -*-
"""
/***************************************************************************
 msta
                                 A QGIS plugin
 Mutli-Sediment Trend Analysis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-03-01
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Emmanuel Poizot
        email                : emmanuel.poizot@lecnam.net
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

UNIT = dict(percent='%', metric='metre', phi='phi', other='undefined')

OPERAND = dict(ou='OR', et='AND', xou='XOR', none='None')

COMP = dict(sup='>', inf='<', eq='==', diff='!=', none='')

GSTAVAR = ["Mean","Sorting","Skewness","mean","sorting","skewness","m","so","sk","M","SO","SK"]

CONTEXTINFO = {1:"Variable(s) information",
               2:"Trend(s) information",
               3:"GSTA variable information",
               4:"GSTA trend(s) information",
               5:"Current selected variable",
               6:"Points information",
               7:"__DEBUG__",
               999:""}

# constante definitions
UPDATEDB = {'varalias' : 0,
            'varrange' : 1,
            'varvalue' : 2,
            'vartrend' : 3,
            'varsearch' : 4}