# -*- coding: utf-8 -*-
"""
/***************************************************************************
 msta
                                 A QGIS plugin
 Mutli-Sediment Trend Analysis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-03-01
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Emmanuel Poizot
        email                : emmanuel.poizot@lecnam.net
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

class config:
    def __init__(self):
        # Unit of variables,must be the same as mstaCoreClass.py definition
        self.UNIT = {
            '%': 'percent',
            'metric': 'metre',
            'phi': 'phi',
            'other': 'unknown'
        }
        # Operand operations, must be same as those defined in mstaCoreClass.py
        self.OPERAND = {
            'ou' : 'OR',
            'et' : 'AND',
            'xou' : 'XOR',
            'none' : 'None'
        }
        # Trend operations
        self.COMP = {
            'sup' : '>',
            'inf' : '<',
            'none' : ''
        }

    def __str__(self):
        print("Variables : UNIT, COMP, OPERAND")


