# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_gsta_trend_definition.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_setGSTATrendCaseDialog(object):
    def setupUi(self, setGSTATrendCaseDialog):
        setGSTATrendCaseDialog.setObjectName("setGSTATrendCaseDialog")
        setGSTATrendCaseDialog.setEnabled(True)
        setGSTATrendCaseDialog.resize(375, 298)
        setGSTATrendCaseDialog.setSizeGripEnabled(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(setGSTATrendCaseDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 260, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.GSTAGroup = QtWidgets.QGroupBox(setGSTATrendCaseDialog)
        self.GSTAGroup.setEnabled(True)
        self.GSTAGroup.setGeometry(QtCore.QRect(10, 10, 341, 241))
        self.GSTAGroup.setAutoFillBackground(False)
        self.GSTAGroup.setStyleSheet("")
        self.GSTAGroup.setFlat(False)
        self.GSTAGroup.setObjectName("GSTAGroup")
        self.gstaCaseListEdit = QtWidgets.QTextEdit(self.GSTAGroup)
        self.gstaCaseListEdit.setEnabled(True)
        self.gstaCaseListEdit.setGeometry(QtCore.QRect(10, 61, 81, 141))
        self.gstaCaseListEdit.setReadOnly(True)
        self.gstaCaseListEdit.setObjectName("gstaCaseListEdit")
        self.buttonRemoveGSTATrendCase = QtWidgets.QPushButton(self.GSTAGroup)
        self.buttonRemoveGSTATrendCase.setGeometry(QtCore.QRect(100, 141, 41, 27))
        self.buttonRemoveGSTATrendCase.setObjectName("buttonRemoveGSTATrendCase")
        self.buttonAddGSTATrendCase = QtWidgets.QPushButton(self.GSTAGroup)
        self.buttonAddGSTATrendCase.setGeometry(QtCore.QRect(100, 91, 41, 27))
        self.buttonAddGSTATrendCase.setObjectName("buttonAddGSTATrendCase")
        self.GSTATrendMeanGroup = QtWidgets.QGroupBox(self.GSTAGroup)
        self.GSTATrendMeanGroup.setGeometry(QtCore.QRect(150, 40, 181, 51))
        self.GSTATrendMeanGroup.setCheckable(False)
        self.GSTATrendMeanGroup.setObjectName("GSTATrendMeanGroup")
        self.widget = QtWidgets.QWidget(self.GSTATrendMeanGroup)
        self.widget.setGeometry(QtCore.QRect(10, 20, 161, 24))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioGSTAMeanFiner = QtWidgets.QRadioButton(self.widget)
        self.radioGSTAMeanFiner.setObjectName("radioGSTAMeanFiner")
        self.gridLayout.addWidget(self.radioGSTAMeanFiner, 0, 0, 1, 1)
        self.radioGSTAMeanCoarser = QtWidgets.QRadioButton(self.widget)
        self.radioGSTAMeanCoarser.setObjectName("radioGSTAMeanCoarser")
        self.gridLayout.addWidget(self.radioGSTAMeanCoarser, 0, 1, 1, 1)
        self.radioGSTAMeanNone = QtWidgets.QRadioButton(self.widget)
        self.radioGSTAMeanNone.setChecked(True)
        self.radioGSTAMeanNone.setObjectName("radioGSTAMeanNone")
        self.gridLayout.addWidget(self.radioGSTAMeanNone, 0, 2, 1, 1)
        self.GSTATrendSortingGroup = QtWidgets.QGroupBox(self.GSTAGroup)
        self.GSTATrendSortingGroup.setGeometry(QtCore.QRect(150, 101, 181, 51))
        self.GSTATrendSortingGroup.setObjectName("GSTATrendSortingGroup")
        self.widget1 = QtWidgets.QWidget(self.GSTATrendSortingGroup)
        self.widget1.setGeometry(QtCore.QRect(10, 20, 161, 24))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioGSTASortingBetter = QtWidgets.QRadioButton(self.widget1)
        self.radioGSTASortingBetter.setObjectName("radioGSTASortingBetter")
        self.gridLayout_2.addWidget(self.radioGSTASortingBetter, 0, 0, 1, 1)
        self.radioGSTASortingPorer = QtWidgets.QRadioButton(self.widget1)
        self.radioGSTASortingPorer.setObjectName("radioGSTASortingPorer")
        self.gridLayout_2.addWidget(self.radioGSTASortingPorer, 0, 1, 1, 1)
        self.radioGSTASortingNone = QtWidgets.QRadioButton(self.widget1)
        self.radioGSTASortingNone.setChecked(True)
        self.radioGSTASortingNone.setObjectName("radioGSTASortingNone")
        self.gridLayout_2.addWidget(self.radioGSTASortingNone, 0, 2, 1, 1)
        self.GSTATrendSkewnessGroup = QtWidgets.QGroupBox(self.GSTAGroup)
        self.GSTATrendSkewnessGroup.setGeometry(QtCore.QRect(150, 161, 181, 51))
        self.GSTATrendSkewnessGroup.setObjectName("GSTATrendSkewnessGroup")
        self.widget2 = QtWidgets.QWidget(self.GSTATrendSkewnessGroup)
        self.widget2.setGeometry(QtCore.QRect(10, 20, 161, 24))
        self.widget2.setObjectName("widget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioGSTASkewnessPlus = QtWidgets.QRadioButton(self.widget2)
        self.radioGSTASkewnessPlus.setObjectName("radioGSTASkewnessPlus")
        self.gridLayout_3.addWidget(self.radioGSTASkewnessPlus, 0, 0, 1, 1)
        self.radioGSTASkewnessMinus = QtWidgets.QRadioButton(self.widget2)
        self.radioGSTASkewnessMinus.setObjectName("radioGSTASkewnessMinus")
        self.gridLayout_3.addWidget(self.radioGSTASkewnessMinus, 0, 1, 1, 1)
        self.radioGSTASkewnessNone = QtWidgets.QRadioButton(self.widget2)
        self.radioGSTASkewnessNone.setChecked(True)
        self.radioGSTASkewnessNone.setObjectName("radioGSTASkewnessNone")
        self.gridLayout_3.addWidget(self.radioGSTASkewnessNone, 0, 2, 1, 1)
        self.GSTATrendSkewnessGroup.raise_()
        self.GSTATrendSortingGroup.raise_()
        self.GSTATrendMeanGroup.raise_()
        self.gstaCaseListEdit.raise_()
        self.buttonRemoveGSTATrendCase.raise_()
        self.buttonAddGSTATrendCase.raise_()

        self.retranslateUi(setGSTATrendCaseDialog)
        self.buttonBox.accepted.connect(setGSTATrendCaseDialog.accept)
        self.buttonBox.rejected.connect(setGSTATrendCaseDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(setGSTATrendCaseDialog)

    def retranslateUi(self, setGSTATrendCaseDialog):
        _translate = QtCore.QCoreApplication.translate
        setGSTATrendCaseDialog.setWindowTitle(_translate("setGSTATrendCaseDialog", "GSTA trends cases"))
        self.GSTAGroup.setTitle(_translate("setGSTATrendCaseDialog", "GSTA Trend case(s) to study"))
        self.gstaCaseListEdit.setHtml(_translate("setGSTATrendCaseDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>"))
        self.buttonRemoveGSTATrendCase.setText(_translate("setGSTATrendCaseDialog", ">>"))
        self.buttonAddGSTATrendCase.setText(_translate("setGSTATrendCaseDialog", "<<"))
        self.GSTATrendMeanGroup.setTitle(_translate("setGSTATrendCaseDialog", "Mean"))
        self.radioGSTAMeanFiner.setText(_translate("setGSTATrendCaseDialog", "F"))
        self.radioGSTAMeanCoarser.setText(_translate("setGSTATrendCaseDialog", "C"))
        self.radioGSTAMeanNone.setText(_translate("setGSTATrendCaseDialog", "None"))
        self.GSTATrendSortingGroup.setTitle(_translate("setGSTATrendCaseDialog", "Sorting"))
        self.radioGSTASortingBetter.setText(_translate("setGSTATrendCaseDialog", "B"))
        self.radioGSTASortingPorer.setText(_translate("setGSTATrendCaseDialog", "P"))
        self.radioGSTASortingNone.setText(_translate("setGSTATrendCaseDialog", "None"))
        self.GSTATrendSkewnessGroup.setTitle(_translate("setGSTATrendCaseDialog", "Skewness"))
        self.radioGSTASkewnessPlus.setText(_translate("setGSTATrendCaseDialog", "+"))
        self.radioGSTASkewnessMinus.setText(_translate("setGSTATrendCaseDialog", "-"))
        self.radioGSTASkewnessNone.setText(_translate("setGSTATrendCaseDialog", "None"))

