# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_gsta_trend_definition.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GSTADlgBase(object):
    def setupUi(self, GSTADlgBase):
        GSTADlgBase.setObjectName("GSTADlgBase")
        GSTADlgBase.setEnabled(True)
        GSTADlgBase.resize(375, 298)
        GSTADlgBase.setSizeGripEnabled(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(GSTADlgBase)
        self.buttonBox.setGeometry(QtCore.QRect(10, 260, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(GSTADlgBase)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 341, 241))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("")
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gstaCaseListEdit = QtWidgets.QTextEdit(self.groupBox)
        self.gstaCaseListEdit.setEnabled(True)
        self.gstaCaseListEdit.setGeometry(QtCore.QRect(10, 61, 81, 141))
        self.gstaCaseListEdit.setReadOnly(True)
        self.gstaCaseListEdit.setObjectName("gstaCaseListEdit")
        self.buttonRemoveGSTATrendCase = QtWidgets.QPushButton(self.groupBox)
        self.buttonRemoveGSTATrendCase.setGeometry(QtCore.QRect(100, 141, 41, 27))
        self.buttonRemoveGSTATrendCase.setObjectName("buttonRemoveGSTATrendCase")
        self.buttonAddGSTATrendCase = QtWidgets.QPushButton(self.groupBox)
        self.buttonAddGSTATrendCase.setGeometry(QtCore.QRect(100, 91, 41, 27))
        self.buttonAddGSTATrendCase.setObjectName("buttonAddGSTATrendCase")
        self.GSTATrendMean = QtWidgets.QGroupBox(self.groupBox)
        self.GSTATrendMean.setGeometry(QtCore.QRect(150, 40, 181, 51))
        self.GSTATrendMean.setObjectName("GSTATrendMean")
        self.GSTATrendSorting = QtWidgets.QGroupBox(self.groupBox)
        self.GSTATrendSorting.setGeometry(QtCore.QRect(150, 101, 181, 51))
        self.GSTATrendSorting.setObjectName("GSTATrendSorting")
        self.GSTATrendSkewness = QtWidgets.QGroupBox(self.groupBox)
        self.GSTATrendSkewness.setGeometry(QtCore.QRect(150, 161, 181, 51))
        self.GSTATrendSkewness.setObjectName("GSTATrendSkewness")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(160, 60, 161, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioGSTAMeanFiner = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioGSTAMeanFiner.setObjectName("radioGSTAMeanFiner")
        self.horizontalLayout.addWidget(self.radioGSTAMeanFiner)
        self.radioGSTAMeanCoarser = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioGSTAMeanCoarser.setObjectName("radioGSTAMeanCoarser")
        self.horizontalLayout.addWidget(self.radioGSTAMeanCoarser)
        self.radioGSTAMeanNone = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioGSTAMeanNone.setChecked(True)
        self.radioGSTAMeanNone.setObjectName("radioGSTAMeanNone")
        self.horizontalLayout.addWidget(self.radioGSTAMeanNone)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(160, 120, 162, 24))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioGSTASortingBetter = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.radioGSTASortingBetter.setObjectName("radioGSTASortingBetter")
        self.horizontalLayout_2.addWidget(self.radioGSTASortingBetter)
        self.radioGSTASortingPorer = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.radioGSTASortingPorer.setObjectName("radioGSTASortingPorer")
        self.horizontalLayout_2.addWidget(self.radioGSTASortingPorer)
        self.radioGSTASortingNone = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.radioGSTASortingNone.setChecked(True)
        self.radioGSTASortingNone.setObjectName("radioGSTASortingNone")
        self.horizontalLayout_2.addWidget(self.radioGSTASortingNone)
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(161, 180, 157, 24))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioGSTASkewnessPositive = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.radioGSTASkewnessPositive.setObjectName("radioGSTASkewnessPositive")
        self.horizontalLayout_3.addWidget(self.radioGSTASkewnessPositive)
        self.radioGSTASkewnessNegative = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.radioGSTASkewnessNegative.setObjectName("radioGSTASkewnessNegative")
        self.horizontalLayout_3.addWidget(self.radioGSTASkewnessNegative)
        self.radioGSTASkewnessNone = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.radioGSTASkewnessNone.setChecked(True)
        self.radioGSTASkewnessNone.setObjectName("radioGSTASkewnessNone")
        self.horizontalLayout_3.addWidget(self.radioGSTASkewnessNone)
        self.layoutWidget_2.raise_()
        self.layoutWidget_3.raise_()
        self.layoutWidget.raise_()
        self.GSTATrendSkewness.raise_()
        self.GSTATrendSorting.raise_()
        self.GSTATrendMean.raise_()
        self.gstaCaseListEdit.raise_()
        self.buttonRemoveGSTATrendCase.raise_()
        self.buttonAddGSTATrendCase.raise_()

        self.retranslateUi(GSTADlgBase)
        self.buttonBox.accepted.connect(GSTADlgBase.accept)
        self.buttonBox.rejected.connect(GSTADlgBase.reject)
        QtCore.QMetaObject.connectSlotsByName(GSTADlgBase)

    def retranslateUi(self, GSTADlgBase):
        _translate = QtCore.QCoreApplication.translate
        GSTADlgBase.setWindowTitle(_translate("GSTADlgBase", "GSTA trends cases"))
        self.groupBox.setTitle(_translate("GSTADlgBase", "GSTA Trend case(s) to study"))
        self.gstaCaseListEdit.setHtml(_translate("GSTADlgBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>"))
        self.buttonRemoveGSTATrendCase.setText(_translate("GSTADlgBase", ">>"))
        self.buttonAddGSTATrendCase.setText(_translate("GSTADlgBase", "<<"))
        self.GSTATrendMean.setTitle(_translate("GSTADlgBase", "Mean"))
        self.GSTATrendSorting.setTitle(_translate("GSTADlgBase", "Sorting"))
        self.GSTATrendSkewness.setTitle(_translate("GSTADlgBase", "Skewness"))
        self.radioGSTAMeanFiner.setText(_translate("GSTADlgBase", "F"))
        self.radioGSTAMeanCoarser.setText(_translate("GSTADlgBase", "C"))
        self.radioGSTAMeanNone.setText(_translate("GSTADlgBase", "None"))
        self.radioGSTASortingBetter.setText(_translate("GSTADlgBase", "B"))
        self.radioGSTASortingPorer.setText(_translate("GSTADlgBase", "P"))
        self.radioGSTASortingNone.setText(_translate("GSTADlgBase", "None"))
        self.radioGSTASkewnessPositive.setText(_translate("GSTADlgBase", "+"))
        self.radioGSTASkewnessNegative.setText(_translate("GSTADlgBase", "-"))
        self.radioGSTASkewnessNone.setText(_translate("GSTADlgBase", "None"))

