# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_multi_sediment_trend_analysis_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(641, 326)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 641, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuVariables = QtWidgets.QMenu(self.menubar)
        self.menuVariables.setObjectName("menuVariables")
        self.menuVariableModify = QtWidgets.QMenu(self.menuVariables)
        self.menuVariableModify.setObjectName("menuVariableModify")
        self.menuVariableDelete = QtWidgets.QMenu(self.menuVariables)
        self.menuVariableDelete.setObjectName("menuVariableDelete")
        self.menuVariableSelect = QtWidgets.QMenu(self.menuVariables)
        self.menuVariableSelect.setObjectName("menuVariableSelect")
        self.menuTrends = QtWidgets.QMenu(self.menubar)
        self.menuTrends.setObjectName("menuTrends")
        self.menuDeleteTrends = QtWidgets.QMenu(self.menuTrends)
        self.menuDeleteTrends.setObjectName("menuDeleteTrends")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFileImport = QtWidgets.QAction(MainWindow)
        self.actionFileImport.setObjectName("actionFileImport")
        self.actionModifyVariablesName = QtWidgets.QAction(MainWindow)
        self.actionModifyVariablesName.setObjectName("actionModifyVariablesName")
        self.actionModifyVariablesUnits = QtWidgets.QAction(MainWindow)
        self.actionModifyVariablesUnits.setObjectName("actionModifyVariablesUnits")
        self.actionVModifyVariablesRange = QtWidgets.QAction(MainWindow)
        self.actionVModifyVariablesRange.setObjectName("actionVModifyVariablesRange")
        self.actionModifyVariableResearchArea = QtWidgets.QAction(MainWindow)
        self.actionModifyVariableResearchArea.setObjectName("actionModifyVariableResearchArea")
        self.actionDeleteAllVariables = QtWidgets.QAction(MainWindow)
        self.actionDeleteAllVariables.setObjectName("actionDeleteAllVariables")
        self.actionDeleteVariables = QtWidgets.QAction(MainWindow)
        self.actionDeleteVariables.setObjectName("actionDeleteVariables")
        self.actionAppQuit = QtWidgets.QAction(MainWindow)
        self.actionAppQuit.setObjectName("actionAppQuit")
        self.actionListAllTrends = QtWidgets.QAction(MainWindow)
        self.actionListAllTrends.setObjectName("actionListAllTrends")
        self.actionTrendsSelection = QtWidgets.QAction(MainWindow)
        self.actionTrendsSelection.setObjectName("actionTrendsSelection")
        self.actionSelectAllVariables = QtWidgets.QAction(MainWindow)
        self.actionSelectAllVariables.setObjectName("actionSelectAllVariables")
        self.actionSelectVariables = QtWidgets.QAction(MainWindow)
        self.actionSelectVariables.setObjectName("actionSelectVariables")
        self.actionModifyTrends = QtWidgets.QAction(MainWindow)
        self.actionModifyTrends.setObjectName("actionModifyTrends")
        self.actionDeleteAllTrends = QtWidgets.QAction(MainWindow)
        self.actionDeleteAllTrends.setObjectName("actionDeleteAllTrends")
        self.actionDeleteTrendsSelection = QtWidgets.QAction(MainWindow)
        self.actionDeleteTrendsSelection.setObjectName("actionDeleteTrendsSelection")
        self.actionSetWorkingDirectory = QtWidgets.QAction(MainWindow)
        self.actionSetWorkingDirectory.setObjectName("actionSetWorkingDirectory")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setCheckable(False)
        self.actionAbout.setObjectName("actionAbout")
        self.actionGSTALikeTrend = QtWidgets.QAction(MainWindow)
        self.actionGSTALikeTrend.setObjectName("actionGSTALikeTrend")
        self.actionGSTA = QtWidgets.QAction(MainWindow)
        self.actionGSTA.setObjectName("actionGSTA")
        self.actionMSTA = QtWidgets.QAction(MainWindow)
        self.actionMSTA.setObjectName("actionMSTA")
        self.actionGSTALikeVariable = QtWidgets.QAction(MainWindow)
        self.actionGSTALikeVariable.setObjectName("actionGSTALikeVariable")
        self.actionList = QtWidgets.QAction(MainWindow)
        self.actionList.setObjectName("actionList")
        self.menuFile.addAction(self.actionFileImport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAppQuit)
        self.menuVariableModify.addAction(self.actionModifyVariablesName)
        self.menuVariableModify.addAction(self.actionModifyVariablesUnits)
        self.menuVariableModify.addAction(self.actionVModifyVariablesRange)
        self.menuVariableModify.addAction(self.actionModifyVariableResearchArea)
        self.menuVariableDelete.addAction(self.actionDeleteAllVariables)
        self.menuVariableDelete.addAction(self.actionDeleteVariables)
        self.menuVariableSelect.addAction(self.actionSelectAllVariables)
        self.menuVariableSelect.addAction(self.actionSelectVariables)
        self.menuVariables.addAction(self.menuVariableSelect.menuAction())
        self.menuVariables.addAction(self.menuVariableModify.menuAction())
        self.menuVariables.addAction(self.menuVariableDelete.menuAction())
        self.menuVariables.addSeparator()
        self.menuVariables.addAction(self.actionGSTALikeVariable)
        self.menuDeleteTrends.addAction(self.actionDeleteAllTrends)
        self.menuDeleteTrends.addAction(self.actionDeleteTrendsSelection)
        self.menuTrends.addAction(self.actionList)
        self.menuTrends.addAction(self.actionModifyTrends)
        self.menuTrends.addAction(self.menuDeleteTrends.menuAction())
        self.menuTrends.addSeparator()
        self.menuTrends.addAction(self.actionGSTALikeTrend)
        self.menuSettings.addAction(self.actionSetWorkingDirectory)
        self.menuHelp.addAction(self.actionAbout)
        self.menuRun.addAction(self.actionMSTA)
        self.menuRun.addAction(self.actionGSTA)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuVariables.menuAction())
        self.menubar.addAction(self.menuTrends.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuVariables.setTitle(_translate("MainWindow", "Variables"))
        self.menuVariableModify.setTitle(_translate("MainWindow", "Modify"))
        self.menuVariableDelete.setTitle(_translate("MainWindow", "Delete"))
        self.menuVariableSelect.setTitle(_translate("MainWindow", "Select"))
        self.menuTrends.setTitle(_translate("MainWindow", "Trends"))
        self.menuDeleteTrends.setTitle(_translate("MainWindow", "Delete"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuRun.setTitle(_translate("MainWindow", "Run"))
        self.actionFileImport.setText(_translate("MainWindow", "Import..."))
        self.actionModifyVariablesName.setText(_translate("MainWindow", "Name..."))
        self.actionModifyVariablesUnits.setText(_translate("MainWindow", "Units..."))
        self.actionVModifyVariablesRange.setText(_translate("MainWindow", "Range..."))
        self.actionModifyVariableResearchArea.setText(_translate("MainWindow", "Research area..."))
        self.actionDeleteAllVariables.setText(_translate("MainWindow", "All..."))
        self.actionDeleteVariables.setText(_translate("MainWindow", "One or more..."))
        self.actionAppQuit.setText(_translate("MainWindow", "Quit"))
        self.actionListAllTrends.setText(_translate("MainWindow", "All"))
        self.actionTrendsSelection.setText(_translate("MainWindow", "Selection..."))
        self.actionSelectAllVariables.setText(_translate("MainWindow", "All"))
        self.actionSelectVariables.setText(_translate("MainWindow", "One or more..."))
        self.actionModifyTrends.setText(_translate("MainWindow", "Modify..."))
        self.actionDeleteAllTrends.setText(_translate("MainWindow", "All"))
        self.actionDeleteTrendsSelection.setText(_translate("MainWindow", "One or more..."))
        self.actionSetWorkingDirectory.setText(_translate("MainWindow", "Set working directory..."))
        self.actionSetWorkingDirectory.setToolTip(_translate("MainWindow", "Set working directory"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionGSTALikeTrend.setText(_translate("MainWindow", "GSTA like trend..."))
        self.actionGSTA.setText(_translate("MainWindow", "GSTA..."))
        self.actionMSTA.setText(_translate("MainWindow", "MSTA..."))
        self.actionGSTALikeVariable.setText(_translate("MainWindow", "GSTA like variables..."))
        self.actionList.setText(_translate("MainWindow", "List"))

