# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_msta_expression_builder_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mstaExpressionBuilderDlg(object):
    def setupUi(self, mstaExpressionBuilderDlg):
        mstaExpressionBuilderDlg.setObjectName("mstaExpressionBuilderDlg")
        mstaExpressionBuilderDlg.resize(479, 268)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mstaExpressionBuilderDlg.setWindowIcon(icon)
        mstaExpressionBuilderDlg.setSizeGripEnabled(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(mstaExpressionBuilderDlg)
        self.buttonBox.setGeometry(QtCore.QRect(280, 230, 181, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(mstaExpressionBuilderDlg)
        self.groupBox.setGeometry(QtCore.QRect(260, 10, 201, 61))
        self.groupBox.setObjectName("groupBox")
        self.splitter_3 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_3.setGeometry(QtCore.QRect(10, 30, 181, 24))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.andRadioButton = QtWidgets.QRadioButton(self.splitter_3)
        self.andRadioButton.setObjectName("andRadioButton")
        self.orRadioButton = QtWidgets.QRadioButton(self.splitter_3)
        self.orRadioButton.setObjectName("orRadioButton")
        self.xorRadioButton = QtWidgets.QRadioButton(self.splitter_3)
        self.xorRadioButton.setObjectName("xorRadioButton")
        self.leftParenthesisButton = QtWidgets.QPushButton(mstaExpressionBuilderDlg)
        self.leftParenthesisButton.setGeometry(QtCore.QRect(15, 70, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.leftParenthesisButton.setFont(font)
        self.leftParenthesisButton.setIconSize(QtCore.QSize(20, 20))
        self.leftParenthesisButton.setObjectName("leftParenthesisButton")
        self.rightParenthesisButton = QtWidgets.QPushButton(mstaExpressionBuilderDlg)
        self.rightParenthesisButton.setGeometry(QtCore.QRect(183, 70, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rightParenthesisButton.setFont(font)
        self.rightParenthesisButton.setObjectName("rightParenthesisButton")
        self.addToolButton = QtWidgets.QToolButton(mstaExpressionBuilderDlg)
        self.addToolButton.setGeometry(QtCore.QRect(105, 80, 31, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/arrowdown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addToolButton.setIcon(icon1)
        self.addToolButton.setIconSize(QtCore.QSize(20, 20))
        self.addToolButton.setObjectName("addToolButton")
        self.addOperandToolButton = QtWidgets.QToolButton(mstaExpressionBuilderDlg)
        self.addOperandToolButton.setGeometry(QtCore.QRect(330, 80, 31, 31))
        self.addOperandToolButton.setIcon(icon1)
        self.addOperandToolButton.setIconSize(QtCore.QSize(20, 20))
        self.addOperandToolButton.setObjectName("addOperandToolButton")
        self.splitter_2 = QtWidgets.QSplitter(mstaExpressionBuilderDlg)
        self.splitter_2.setGeometry(QtCore.QRect(10, 120, 451, 101))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        self.label_2.setObjectName("label_2")
        self.expressionTextEdit = QtWidgets.QTextEdit(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.expressionTextEdit.setFont(font)
        self.expressionTextEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.expressionTextEdit.setObjectName("expressionTextEdit")
        self.splitter = QtWidgets.QSplitter(mstaExpressionBuilderDlg)
        self.splitter.setGeometry(QtCore.QRect(14, 10, 211, 51))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.definedTrendCaseComboBox = QtWidgets.QComboBox(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.definedTrendCaseComboBox.setFont(font)
        self.definedTrendCaseComboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAfterCurrent)
        self.definedTrendCaseComboBox.setObjectName("definedTrendCaseComboBox")

        self.retranslateUi(mstaExpressionBuilderDlg)
        self.buttonBox.accepted.connect(mstaExpressionBuilderDlg.accept)
        self.buttonBox.rejected.connect(mstaExpressionBuilderDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(mstaExpressionBuilderDlg)

    def retranslateUi(self, mstaExpressionBuilderDlg):
        _translate = QtCore.QCoreApplication.translate
        mstaExpressionBuilderDlg.setWindowTitle(_translate("mstaExpressionBuilderDlg", "Build expression dialog"))
        self.groupBox.setTitle(_translate("mstaExpressionBuilderDlg", "Operand"))
        self.andRadioButton.setText(_translate("mstaExpressionBuilderDlg", "AND"))
        self.orRadioButton.setText(_translate("mstaExpressionBuilderDlg", "OR"))
        self.xorRadioButton.setText(_translate("mstaExpressionBuilderDlg", "XOR"))
        self.leftParenthesisButton.setText(_translate("mstaExpressionBuilderDlg", "("))
        self.rightParenthesisButton.setText(_translate("mstaExpressionBuilderDlg", ")"))
        self.addToolButton.setText(_translate("mstaExpressionBuilderDlg", "Add"))
        self.addOperandToolButton.setText(_translate("mstaExpressionBuilderDlg", "Add"))
        self.label_2.setText(_translate("mstaExpressionBuilderDlg", "Expression"))
        self.label.setText(_translate("mstaExpressionBuilderDlg", "Defined trend cases"))

