# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_msta_text_file_analysis.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_msta_text_file_analysis(object):
    def setupUi(self, msta_text_file_analysis):
        msta_text_file_analysis.setObjectName("msta_text_file_analysis")
        msta_text_file_analysis.resize(671, 552)
        self.buttonBox = QtWidgets.QDialogButtonBox(msta_text_file_analysis)
        self.buttonBox.setGeometry(QtCore.QRect(310, 520, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(msta_text_file_analysis)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 631, 101))
        self.groupBox.setObjectName("groupBox")
        self.radioSpace = QtWidgets.QRadioButton(self.groupBox)
        self.radioSpace.setGeometry(QtCore.QRect(20, 30, 86, 22))
        self.radioSpace.setChecked(True)
        self.radioSpace.setObjectName("radioSpace")
        self.radioTabulation = QtWidgets.QRadioButton(self.groupBox)
        self.radioTabulation.setGeometry(QtCore.QRect(120, 30, 120, 22))
        self.radioTabulation.setObjectName("radioTabulation")
        self.radioComma = QtWidgets.QRadioButton(self.groupBox)
        self.radioComma.setGeometry(QtCore.QRect(260, 30, 104, 22))
        self.radioComma.setObjectName("radioComma")
        self.radioSimilicon = QtWidgets.QRadioButton(self.groupBox)
        self.radioSimilicon.setGeometry(QtCore.QRect(390, 30, 113, 22))
        self.radioSimilicon.setObjectName("radioSimilicon")
        self.radioPipe = QtWidgets.QRadioButton(self.groupBox)
        self.radioPipe.setGeometry(QtCore.QRect(510, 30, 84, 22))
        self.radioPipe.setObjectName("radioPipe")
        self.radioOther = QtWidgets.QRadioButton(self.groupBox)
        self.radioOther.setGeometry(QtCore.QRect(21, 63, 86, 22))
        self.radioOther.setObjectName("radioOther")
        self.lineEditOther = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditOther.setEnabled(False)
        self.lineEditOther.setGeometry(QtCore.QRect(113, 61, 129, 27))
        self.lineEditOther.setObjectName("lineEditOther")
        self.groupBox_2 = QtWidgets.QGroupBox(msta_text_file_analysis)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 130, 631, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 31, 611, 28))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBoxHeader = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBoxHeader.setObjectName("checkBoxHeader")
        self.gridLayout.addWidget(self.checkBoxHeader, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.spinBoxSkipLine = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxSkipLine.setObjectName("spinBoxSkipLine")
        self.gridLayout.addWidget(self.spinBoxSkipLine, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 5, 1, 1)
        self.checkBoxCommaSeparator = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBoxCommaSeparator.setEnabled(False)
        self.checkBoxCommaSeparator.setObjectName("checkBoxCommaSeparator")
        self.gridLayout.addWidget(self.checkBoxCommaSeparator, 0, 6, 1, 1)
        self.tableAnalysisResult = QtWidgets.QTableWidget(msta_text_file_analysis)
        self.tableAnalysisResult.setGeometry(QtCore.QRect(20, 320, 631, 191))
        self.tableAnalysisResult.setObjectName("tableAnalysisResult")
        self.tableAnalysisResult.setColumnCount(0)
        self.tableAnalysisResult.setRowCount(0)
        self.groupBox_3 = QtWidgets.QGroupBox(msta_text_file_analysis)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 210, 301, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.xCoordComboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.xCoordComboBox.setGeometry(QtCore.QRect(10, 50, 131, 25))
        self.xCoordComboBox.setObjectName("xCoordComboBox")
        self.yCoordComboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.yCoordComboBox.setGeometry(QtCore.QRect(160, 50, 131, 25))
        self.yCoordComboBox.setObjectName("yCoordComboBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 41, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(160, 30, 41, 17))
        self.label_4.setObjectName("label_4")
        self.sampleNameGroupBox = QtWidgets.QGroupBox(msta_text_file_analysis)
        self.sampleNameGroupBox.setEnabled(True)
        self.sampleNameGroupBox.setGeometry(QtCore.QRect(330, 229, 191, 71))
        self.sampleNameGroupBox.setCheckable(True)
        self.sampleNameGroupBox.setChecked(False)
        self.sampleNameGroupBox.setObjectName("sampleNameGroupBox")
        self.sampleNameComboBox = QtWidgets.QComboBox(self.sampleNameGroupBox)
        self.sampleNameComboBox.setEnabled(False)
        self.sampleNameComboBox.setGeometry(QtCore.QRect(10, 30, 161, 25))
        self.sampleNameComboBox.setObjectName("sampleNameComboBox")
        self.groupBox_4 = QtWidgets.QGroupBox(msta_text_file_analysis)
        self.groupBox_4.setGeometry(QtCore.QRect(530, 209, 120, 91))
        self.groupBox_4.setObjectName("groupBox_4")
        self.numberofLinesToRead = QtWidgets.QSpinBox(self.groupBox_4)
        self.numberofLinesToRead.setGeometry(QtCore.QRect(10, 30, 91, 25))
        self.numberofLinesToRead.setProperty("showGroupSeparator", False)
        self.numberofLinesToRead.setMaximum(10000)
        self.numberofLinesToRead.setProperty("value", 20)
        self.numberofLinesToRead.setObjectName("numberofLinesToRead")
        self.allLinesToRead = QtWidgets.QCheckBox(self.groupBox_4)
        self.allLinesToRead.setGeometry(QtCore.QRect(10, 60, 83, 22))
        self.allLinesToRead.setObjectName("allLinesToRead")

        self.retranslateUi(msta_text_file_analysis)
        self.buttonBox.accepted.connect(msta_text_file_analysis.accept)
        self.buttonBox.rejected.connect(msta_text_file_analysis.reject)
        self.allLinesToRead.toggled['bool'].connect(self.numberofLinesToRead.setDisabled)
        self.radioOther.toggled['bool'].connect(self.lineEditOther.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(msta_text_file_analysis)

    def retranslateUi(self, msta_text_file_analysis):
        _translate = QtCore.QCoreApplication.translate
        msta_text_file_analysis.setWindowTitle(_translate("msta_text_file_analysis", "Dialog"))
        self.groupBox.setTitle(_translate("msta_text_file_analysis", "Separator"))
        self.radioSpace.setText(_translate("msta_text_file_analysis", "Space ( )"))
        self.radioTabulation.setText(_translate("msta_text_file_analysis", "Tabulation (t)"))
        self.radioComma.setText(_translate("msta_text_file_analysis", "Comma ( , )"))
        self.radioSimilicon.setText(_translate("msta_text_file_analysis", "Similicon ( ; )"))
        self.radioPipe.setText(_translate("msta_text_file_analysis", "Pipe ( | )"))
        self.radioOther.setText(_translate("msta_text_file_analysis", "Other(s)"))
        self.groupBox_2.setTitle(_translate("msta_text_file_analysis", "Line treatments"))
        self.checkBoxHeader.setText(_translate("msta_text_file_analysis", "First line as header"))
        self.label.setText(_translate("msta_text_file_analysis", "Skip"))
        self.label_2.setText(_translate("msta_text_file_analysis", "line(s)"))
        self.checkBoxCommaSeparator.setText(_translate("msta_text_file_analysis", "Comma decimal separator"))
        self.groupBox_3.setTitle(_translate("msta_text_file_analysis", "Coordinates"))
        self.label_3.setText(_translate("msta_text_file_analysis", "X field"))
        self.label_4.setText(_translate("msta_text_file_analysis", "Y field"))
        self.sampleNameGroupBox.setTitle(_translate("msta_text_file_analysis", "Sample name field"))
        self.groupBox_4.setTitle(_translate("msta_text_file_analysis", "Lines to read"))
        self.allLinesToRead.setText(_translate("msta_text_file_analysis", "All"))
