# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_msta_variable_definition.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SetMSTAVarOptionsDlg(object):
    def setupUi(self, SetMSTAVarOptionsDlg):
        SetMSTAVarOptionsDlg.setObjectName("SetMSTAVarOptionsDlg")
        SetMSTAVarOptionsDlg.resize(351, 376)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SetMSTAVarOptionsDlg.sizePolicy().hasHeightForWidth())
        SetMSTAVarOptionsDlg.setSizePolicy(sizePolicy)
        self.buttonBox = QtWidgets.QDialogButtonBox(SetMSTAVarOptionsDlg)
        self.buttonBox.setGeometry(QtCore.QRect(150, 320, 191, 61))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(SetMSTAVarOptionsDlg)
        self.groupBox.setGeometry(QtCore.QRect(10, 150, 331, 181))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 90, 311, 80))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.directionVariableLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.directionVariableLineEdit.setGeometry(QtCore.QRect(10, 50, 113, 24))
        self.directionVariableLineEdit.setObjectName("directionVariableLineEdit")
        self.tolangVariableLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.tolangVariableLineEdit.setGeometry(QtCore.QRect(140, 50, 113, 24))
        self.tolangVariableLineEdit.setObjectName("tolangVariableLineEdit")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(140, 30, 164, 15))
        self.label_7.setObjectName("label_7")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 221, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.variableDgLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.variableDgLineEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.variableDgLineEdit.setClearButtonEnabled(False)
        self.variableDgLineEdit.setObjectName("variableDgLineEdit")
        self.horizontalLayout.addWidget(self.variableDgLineEdit)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 141, 16))
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(SetMSTAVarOptionsDlg)
        self.label.setGeometry(QtCore.QRect(10, 10, 35, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(SetMSTAVarOptionsDlg)
        self.label_2.setGeometry(QtCore.QRect(150, 10, 29, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(SetMSTAVarOptionsDlg)
        self.label_3.setGeometry(QtCore.QRect(270, 10, 25, 16))
        self.label_3.setObjectName("label_3")
        self.variableAliasLineEdit = QtWidgets.QLineEdit(SetMSTAVarOptionsDlg)
        self.variableAliasLineEdit.setGeometry(QtCore.QRect(149, 30, 111, 24))
        self.variableAliasLineEdit.setObjectName("variableAliasLineEdit")
        self.variableUnitComboBox = QtWidgets.QComboBox(SetMSTAVarOptionsDlg)
        self.variableUnitComboBox.setGeometry(QtCore.QRect(270, 30, 74, 24))
        self.variableUnitComboBox.setObjectName("variableUnitComboBox")
        self.variableUnitComboBox.addItem("")
        self.variableUnitComboBox.addItem("")
        self.variableUnitComboBox.addItem("")
        self.variableUnitComboBox.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(SetMSTAVarOptionsDlg)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 60, 291, 80))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.splitter_2 = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter_2.setGeometry(QtCore.QRect(10, 40, 261, 24))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_4 = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pmVariableRangeLineEdit = QtWidgets.QLineEdit(self.splitter_2)
        self.pmVariableRangeLineEdit.setObjectName("pmVariableRangeLineEdit")
        self.variableNameComboBox = QtWidgets.QComboBox(SetMSTAVarOptionsDlg)
        self.variableNameComboBox.setGeometry(QtCore.QRect(10, 30, 131, 23))
        self.variableNameComboBox.setObjectName("variableNameComboBox")

        self.retranslateUi(SetMSTAVarOptionsDlg)
        self.buttonBox.accepted.connect(SetMSTAVarOptionsDlg.accept)
        self.buttonBox.rejected.connect(SetMSTAVarOptionsDlg.reject)
        self.variableDgLineEdit.textChanged['QString'].connect(self.tolangVariableLineEdit.setText)
        QtCore.QMetaObject.connectSlotsByName(SetMSTAVarOptionsDlg)

    def retranslateUi(self, SetMSTAVarOptionsDlg):
        _translate = QtCore.QCoreApplication.translate
        SetMSTAVarOptionsDlg.setWindowTitle(_translate("SetMSTAVarOptionsDlg", "MSTA variable definition"))
        self.groupBox.setTitle(_translate("SetMSTAVarOptionsDlg", "Options"))
        self.groupBox_3.setTitle(_translate("SetMSTAVarOptionsDlg", "Anysotropy"))
        self.label_6.setText(_translate("SetMSTAVarOptionsDlg", "Direction (°)"))
        self.label_7.setText(_translate("SetMSTAVarOptionsDlg", "Tolerance (in dataset units)"))
        self.label_9.setText(_translate("SetMSTAVarOptionsDlg", "In dataset units"))
        self.label_8.setText(_translate("SetMSTAVarOptionsDlg", "Characteristic distance"))
        self.label.setText(_translate("SetMSTAVarOptionsDlg", "Name"))
        self.label_2.setText(_translate("SetMSTAVarOptionsDlg", "Alias"))
        self.label_3.setText(_translate("SetMSTAVarOptionsDlg", "Unit"))
        self.variableUnitComboBox.setCurrentText(_translate("SetMSTAVarOptionsDlg", "%"))
        self.variableUnitComboBox.setItemText(0, _translate("SetMSTAVarOptionsDlg", "%"))
        self.variableUnitComboBox.setItemText(1, _translate("SetMSTAVarOptionsDlg", "metric"))
        self.variableUnitComboBox.setItemText(2, _translate("SetMSTAVarOptionsDlg", "phi"))
        self.variableUnitComboBox.setItemText(3, _translate("SetMSTAVarOptionsDlg", "other"))
        self.groupBox_2.setTitle(_translate("SetMSTAVarOptionsDlg", "Range"))
        self.label_4.setText(_translate("SetMSTAVarOptionsDlg", "VALUE"))
        self.label_5.setText(_translate("SetMSTAVarOptionsDlg", "+ / -"))

